<?php

//$actions = array('view' => '', 'edit' => '', 'delete' => '');

$actions = array(
    'issue invoice' => $this->url(array('controller' => 'invoice', 'action' => 'create'),null,TRUE),
    'view invoice' => $this->url(array('controller' => 'invoice', 'action' => 'view'), null, TRUE)
);

echo $this->searchFormTable($this)->getSearchFormTable($this->headerColMap);

// Batch Invoice Run Button
echo '<div style="float:right;"><input onclick="showDialog();" type="button" value="Batch Run" /></div>';

echo $this->listTable($this)->getListTable($this->headerColMap, $this->data, $actions, $pager = true);

?>
<!--  Dialog Pop Up for batch invoice run   -->
<div id="batchInvoiceRunDialog" style="display: none;" title="Invoice Batch Run Variables">
     <form id="batchInvoiceDialogForm" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
         <table>
             <tr>
                 <td style="width:40%">Building</td>
                 <td style="width:60%"><?php echo $this->form->getElement('Bul_Id');  ?></td>
             </tr>
             <tr>
                 <td>Bath Run Number</td>
                 <td><?php echo $this->form->getElement('batchNumber');  ?></td>
             </tr>
             <tr>
                 <td>Overwrite Existing Invoices? (If already created)</td>
                 <td><?php echo $this->form->getElement('overwrite');  ?></td>
             </tr>
             <tr>
                 <td></td>
                 <td><?php echo $this->form->getElement('submit');  ?></td>
             </tr>
         </table>
     </form>
</div>

<!--  Dialog Pop Up for individual invoice run   -->
<div id="individualInvoiceRunDialog" style="display: none;" title="Individual Invoice Variables">
    <form id="individualInvoiceDialogForm" action="<?php echo $this->baseUrl() . '/invoice/create'; ?>" method="post">
        <table>
            <input type="hidden" id="Met_Id" name="Met_Id" />
            <tr>
                <td style="width:50%">Last Invoice? (Terminating tenant)</td>
                <td style="width:50%"><input onclick="showTerminationDate();" type="checkbox" id="terminate" name="terminate" value="1" /></td>
            </tr>
            <tr id="chargeStartDateRow" style="display:none;">
                <td>Charge Start Date</td>
                <td>
                    <input type="text" name="chargeStartDate" id="chargeStartDate" />
                </td>
            </tr>
            <tr id="terminationDate" style="display:none;">
                <td>Date Of Termination</td>
                <td><input type="text" name="Sho_TerminatedDate" id="Sho_TerminatedDate" /></td>
            </tr>
            <tr>
                <td>Overwrite Existing Invoices? (If already created)</td>
                <td>
                    <input type="checkbox" checked="checked" id="overwrite" name="overwrite" value="1" /></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="RUN INVOICE" /></td>
            </tr>
        </table>
    </form>
</div>

<script>
    var baseUrl = "<?php echo $this->baseUrl(); ?>";
    $(function () {
        $("#Met_LastReadDate,#Met_CurrentReadDate").datepicker(
            {
                showOn:"both",
                buttonImage:baseUrl + "/images/b_calendar.png",
                buttonImageOnly:true,
                buttonText:"Select date",
                dateFormat: "yy-mm-dd"
            }
        );
    });

    function showDialog(){
        $("#batchInvoiceRunDialog").dialog(
            {
                modal:true,
                width:430,
                create:function (event, ui) {
                    $("#batchNumber").datepicker(
                        {
                            showOn:"both",
                            buttonImage:baseUrl + "/images/b_calendar.png",
                            buttonImageOnly:true,
                            buttonText:"Select date",
                            dateFormat:"ymm"
                        }
                    );
                },
                close:function (event, ui) {
                    $("#batchInvoiceDialogForm")[0].reset();
                }
            }
        );
    }

    function showInvoiceDialog(id) {
        $("#individualInvoiceRunDialog").dialog(
            {
                modal:true,
                width:450,
                create:function (event, ui) {
                    $("#Met_Id").val(id);
                    $("#Sho_TerminatedDate,#chargeStartDate").datepicker(
                        {
                            showOn:"both",
                            buttonImage:baseUrl + "/images/b_calendar.png",
                            buttonImageOnly:true,
                            buttonText:"Select date",
                            dateFormat:"yy-mm-dd"
                        }
                    );
                },
                beforeClose:function(event, ui){

                    $("#individualInvoiceDialogForm")[0].reset();
                    $("#terminationDate,#chargeStartDateRow").hide();

                }
            }
        );
    }

    function showTerminationDate(){
        if($("#terminate:checked").val() == 1){
             $("#terminationDate,#chargeStartDateRow").show();
        }else{
             $("#Sho_TerminatedDate,#chargeStartDate").val("");
             $("#terminationDate,#chargeStartDateRow").hide();
        }
    }

</script>