<head>

    <meta charset="utf-8">
    <meta content="" name="Title">
    <meta content="" name="description">
    <meta content="" name="keywords">
    <meta content="" name="author">


    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.11.2.custom/jquery-ui.css">
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.11.1.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.11.2.custom/jquery-ui.js"></script>

    <?php echo $this->facebook()->meta();  ?>
    <?php if (!$this->facebook()->isOgImages()) { ?>
       <meta property="og:image" content="<?php echo $this->fullUrl() . '/images/banner-dummy1.jpg' ?>" />
    <?php } ?>

    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/custom/style.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/custom/listtable.css" />
    <title></title>

    <?php
    echo $this->headScript();
    echo $this->headLink();
    echo $this->headStyle();
    ?>

</head>