<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">

    <table>
        <?php echo $this->form->getElement('Ret_Id'); ?>
        <tr>
            <td>Name</td>
            <td><?php echo $this->form->getElement('Ret_Name');  ?></td>
        </tr>
        <tr>
            <td>Address 1</td>
            <td><?php echo $this->form->getElement('Ret_Address1');  ?></td>
        </tr>
        <tr>
            <td>Address 2</td>
            <td><?php echo $this->form->getElement('Ret_Address2');  ?></td>
        </tr>
        <tr>
            <td>Postal Code</td>
            <td><?php echo $this->form->getElement('Ret_PostalCode');  ?></td>
        </tr>
        <tr>
            <td>Telephone</td>
            <td><?php echo $this->form->getElement('Ret_Telephone');  ?></td>
        </tr>
        <tr>
            <td>Facsimile</td>
            <td><?php echo $this->form->getElement('Ret_Facsimile');  ?></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><?php echo $this->form->getElement('Ret_Email');  ?></td>
        </tr>
        <tr>
            <td>Registration No</td>
            <td><?php echo $this->form->getElement('Ret_RegistrationNo');  ?></td>
        </tr>
        <tr>
            <td colspan="2"><?php echo $this->form->getElement('submit');  ?></td>
        </tr>
    </table>

</form>