<?php echo $this->partial("partials/doctype.phtml"); ?>

<html>
<?php echo $this->partial("partials/head.phtml"); ?>

<body>
<?php echo $this->partial("partials/header.phtml"); ?>

<h1>Welcome to Index Page</h1>

<div id="msgs" class="success msg">
    <?php
       if (!empty($this->message->success)){
           echo $this->message->success;
           unset($this->message->success);
       }
    ?>
</div>
<div id="errs" class="error msg">
    <?php
    if (!empty($this->message->error)) {
        echo $this->message->error;
        unset($this->message->error);
    }
    ?>
</div>
<div id="container">
    <div class="content">
        <?php echo $this->layout()->content; ?>
    </div>
</div>

<?php echo $this->partial("partials/footer.phtml"); ?>
</body>

<?php echo $this->partial("partials/scripts.phtml"); ?>

</html>